# Generated by Django 5.1.1 on 2024-09-08 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HabrHubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('hub_link', models.CharField(max_length=100)),
                ('check_interval', models.PositiveBigIntegerField()),
                ('last_check_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HabrLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('title', models.CharField(null=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('author_name', models.CharField(null=True)),
                ('author_link', models.CharField(null=True)),
                ('from_hub', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='habr_parser_info.habrhubs')),
            ],
        ),
    ]
