# Generated by Django 5.1.1 on 2024-09-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habr_parser_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habrhubs',
            name='status',
            field=models.CharField(choices=[('processed', 'Processed'), ('error', 'Error')], default='processed', max_length=10),
        ),
        migrations.AddField(
            model_name='habrlinks',
            name='article',
            field=models.PositiveBigIntegerField(default=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habrlinks',
            name='main_text',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='habrlinks',
            name='status',
            field=models.CharField(choices=[('processed', 'Processed'), ('error', 'Error')], default='processed', max_length=10),
        ),
    ]
