# Generated by Django 5.1.1 on 2024-09-09 20:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habr_parser_info', '0002_habrhubs_status_habrlinks_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habrlinks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habrhubs',
            name='last_check_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
