# Generated by Django 5.1.1 on 2024-09-09 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habr_parser_info', '0003_habrlinks_created_at_alter_habrhubs_last_check_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habrlinks',
            name='from_hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='habr_parser_info.habrhubs'),
        ),
    ]
