# Generated by Django 5.1.1 on 2024-09-09 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habr_parser_info', '0004_alter_habrlinks_from_hub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habrlinks',
            name='from_hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='habr_parser_info.habrhubs'),
        ),
    ]
