# Generated by Django 5.1.1 on 2024-09-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habr_parser_info', '0005_alter_habrlinks_from_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='habrhubs',
            name='count_links_per_page',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='habrhubs',
            name='max_pages',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='habrhubs',
            name='max_threads',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='habrlinks',
            name='from_hub_link',
            field=models.CharField(default='test'),
            preserve_default=False,
        ),
    ]
