# Generated by Django 5.1.1 on 2024-09-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habr_parser_info', '0007_remove_habrhubs_count_links_per_page_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habrhubs',
            old_name='check_interval',
            new_name='check_interval_secs',
        ),
        migrations.AddField(
            model_name='habrhubs',
            name='batch_size',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='habrhubs',
            name='count_links_per_page',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='habrhubs',
            name='max_pages',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='habrhubs',
            name='max_threads',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='habrhubs',
            name='status',
            field=models.CharField(choices=[('processed', 'Processed'), ('error', 'Error'), ('at_work', 'At Work')], default='processed', max_length=10),
        ),
        migrations.AlterField(
            model_name='habrlinks',
            name='status',
            field=models.CharField(choices=[('processed', 'Processed'), ('error', 'Error'), ('at_work', 'At Work')], default='processed', max_length=10),
        ),
    ]
