# Generated by Django 5.1.1 on 2024-09-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habr_parser_info', '0009_habrhubs_next_check_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habrlinks',
            name='link',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
