# Generated by Django 5.1.1 on 2024-09-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habr_parser_info', '0010_alter_habrlinks_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habrlinks',
            name='article',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='habrlinks',
            name='link',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='habrlinks',
            index=models.Index(fields=['article'], name='habr_parser_article_ad47f2_idx'),
        ),
    ]
